=== Victaria/Restaurant-App_for_Executives/src/sample/XML/Product.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
    <xs:element name="products">
        <xs:complexType>
            <xs:sequence>
               <xs:element name="product" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:int" />
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="price" type="xs:double" />
                            <xs:element name="amount" type="xs:int" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Victaria/Restaurant-App_for_Executives/DataBase/ProductsXML.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<products schemaLocation="Product.xsd">
	<product id="1">
		<name></name>
		<price></price>
		<amount></amount>
	</product>
	<product id="2">
		<name></name>
		<price></price>
		<amount></amount>
	</product>
	<product id="3">
		<name></name>
		<price></price>
		<amount></amount>
	</product>
	<product id="4">
		<name></name>
		<price></price>
		<amount></amount>
	</product>
	<product id="5">
		<name></name>
		<price></price>
		<amount></amount>
	</product>
	<product id="6">
		<name></name>
		<price></price>
		<amount></amount>
	</product>
	<product id="7">
		<name></name>
		<price></price>
		<amount></amount>
	</product>
</products>
